Repository TheHikuro/ESGI-Gaming-Association, pull requests merged in 2021-11, with the labels that each got.

#4 Create ORM skeleton :
  config/packages/security.yaml
  src/Entity/Association/Association.php
  src/Entity/Association/Event.php
  src/Entity/User/Section.php
  src/Entity/User/User.php
  src/Repository/Association/AssociationRepository.php
  src/Repository/Association/EventRepository.php
  src/Repository/User/SectionRepository.php
  src/Repository/User/UserRepository.php
Labels: feature

#10 Fix docker composer & add volumes
  .docker/build/php-fpm/Dockerfile
  .docker/conf/php-fpm/apache2.conf
  .docker/conf/php-fpm/sites-enabled/default.conf
  Makefile
  docker-compose.yml
Labels: bug

#11 first_step_auth
  .DS_Store
  config/packages/security.yaml
  config/routes/annotations.yaml
  docker-compose.yml
  migrations/Version20211126141528.php
  migrations/Version20211126183435.php
  src/Controller/Admin/AdminController.php
  src/Controller/Default/LoginController.php
  src/Controller/Default/RegistrationController.php
  src/Controller/User/UserController.php
  src/Entity/Association/Association.php
  src/Entity/Association/Event.php
  src/Entity/User/User.php
  src/Form/RegistrationFormType.php
  src/Repository/User/UserRepository.php
  templates/admin/index.html.twig
  templates/base.html.twig
  templates/login/index.html.twig
  templates/registration/register.html.twig
  templates/user/index.html.twig
Labels: bug, feature, fix

#13 Feature/navbar
  config/packages/security.yaml
  config/routes/annotations.yaml
  postcss.config.js
  public/img/ESGI-logo.png
  public/img/Line.svg
  src/Controller/HomePageController.php
  tailwind.config.js
  templates/base.html.twig
  templates/home_page/index.html.twig
  templates/navbar.html.twig
Labels: feature
