Repository TheHikuro/ESGI-Gaming-Association, pull requests merged in 2021-12, with the labels that each got.

#14 Add front login
  package-lock.json
  package.json
  public/img/background.jpeg
  templates/login/index.html.twig
Labels: feature

#15 Fix/navbar
  Procfile
  composer.json
  composer.lock
  templates/navbar.html.twig
Labels: fix

#16 Add htaccess for heroku
  composer.json
  composer.lock
  config/packages/security.yaml
  public/.htaccess
  symfony.lock
  templates/navbar.html.twig
Labels: feature

#17 Feature/registertemplate
  src/Form/RegistrationFormType.php
  tailwind.config.js
  templates/login/index.html.twig
  templates/registration/register.html.twig
Labels: feature

#19 Edit preprod database env vars
  .env
Labels: feature

#18 Add React js to project
  assets/app.js
  assets/js/app.js
  assets/js/components/modal.js
  assets/js/scrollReveal.js
  package-lock.json
  package.json
  tailwind.config.js
  templates/navbar.html.twig
  templates/user/index.html.twig
  webpack.config.js
Labels: feature

#20 Add automatic database migration to heroku
  composer.json
Labels: feature

#21 feature/dynamicUrlForUser
  .gitignore
  config/routes/annotations.yaml
  src/Controller/UserUrl/UserUrlController.php
  src/Repository/User/UserRepository.php
  src/Service/User/UserService.php
  templates/base.html.twig
  templates/user_url/error_username.html.twig
  templates/user_url/index.html.twig
Labels: feature, OK to review
