Repository TheHikuro/ESGI-Gaming-Association, pull requests merged in 2022-05, with the labels that each got.

#24 add mailer -> confirm account
  composer.json
  composer.lock
  config/bundles.php
  config/packages/dev/swiftmailer.yaml
  config/packages/security.yaml
  config/packages/swiftmailer.yaml
  config/packages/test/swiftmailer.yaml
  docker-compose.yml
  src/Controller/Default/AccountConfirmationController.php
  src/Controller/Default/RegistrationController.php
  src/Entity/User/User.php
  symfony.lock
  templates/email/userConfirmationRegisterEmail.html.twig
  templates/email/userRecoverEmail.html.twig
  templates/login/index.html.twig
  templates/login/recover.html.twig
  templates/login/recover_account.html.twig
Labels: OK to merge

#26 add fixtures section and user
  composer.json
  composer.lock
  config/bundles.php
  src/DataFixtures/AppFixtures.php
  symfony.lock
Labels: OK to review

#27 add api controller
  config/packages/security.yaml
  config/routes/annotations.yaml
  src/Controller/Api/ApiController.php
  src/Controller/Api/User/UserController.php
  src/Controller/Default/HomePageController.php
  src/Controller/UserUrl/UserUrlController.php
  src/Entity/User/User.php
  templates/admin/index.html.twig
Labels: enhancement

#28 Add routes to Api
  src/Controller/Api/ApiController.php
  src/Controller/Api/AssociationController.php
  src/Controller/Api/SectionController.php
  src/Controller/Api/User/UserController.php
  src/Controller/Api/UserController.php
Labels: enhancement

#29 add route user/sendmail to Api
  config/packages/swiftmailer.yaml
  src/Controller/Api/ApiController.php
  src/Controller/Api/AssociationController.php
  src/Controller/Api/SectionController.php
  src/Controller/Api/UserController.php
Labels: enhancement
